export const BASKET_ADD_ITEM = "BASKET_ADD_ITEM";
export const BASKET_REMOVE_ITEM = "BASKET_REMOVE_ITEM";
export const BASKET_SAVE_SHIPPING_ADDRESS = "BASKET_SAVE_SHIPPING_ADDRESS";
export const BASKET_SAVE_PAYMENT_METHOD = "BASKET_SAVE_PAYMENT_METHOD";

export const GET_USER_BASKET_REQUEST = "GET_USER_BASKET_REQUEST";
export const GET_USER_BASKET_SUCCESS = "GET_USER_BASKET_SUCCESS";
export const GET_USER_BASKET_FAIL = "GET_USER_BASKET_FAIL";
export const GET_USER_BASKET_CLEAR = "GET_USER_BASKET_CLEAR";
